name: shoppi_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: any
  flutter_gen_runner:
  build_runner: ^2.3.2


flutter_gen:
  output: lib/cores/gen/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/features/home/assets/
    